import java.io.FileOutputStream;
import java.io.ObjectOutputStream;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

public class AddTeam {
	public static void main(String[] args) {
		Map<String, Team> teams = new HashMap<>();
		List<Team> list = new LinkedList<>();
		String root = "/Users/Steveisno1/Documents/XJBjava/DrawSimulator/team icons/";
		Team t1 = new Team("Real Madrid", "Spain", 1, root + "Real-Madrid.png");
		teams.put(t1.name, t1);
		Team t2 = new Team("Bayern Munich", "Germany", 1, root + "FC_Bayern_Munich.png");
		teams.put(t2.name, t2);
		Team t3 = new Team("Chelsea", "England", 1, root + "Chelsea_FC.png");
		teams.put(t3.name, t3);
		Team t4 = new Team("Juventus", "Italy", 1, root + "Juventus.png");
		teams.put(t4.name, t4);
		Team t5 = new Team("Benfica", "Portugal", 1, root + "SL_Benfica.png");
		teams.put(t5.name, t5);
		Team t6 = new Team("Monaco", "France", 1, root + "AS_Monaco.png");
		teams.put(t6.name, t6);
		Team t7 = new Team("Spartak Moscow", "Russia", 1, root + "FC_Spartak_Moscow.png");
		teams.put(t7.name, t7);
		Team t8 = new Team("Shakhtar Donetsk", "Ukraine", 1, root + "FC_Shakhtar_Donetsk.png");
		teams.put(t8.name, t8);
		Team t9 = new Team("Barcelona", "Spain", 2, root + "Fc_barcelona.png");
		teams.put(t9.name, t9);
		Team t10 = new Team("Atletico Madrid", "Spain", 2, root + "Atletico_Madrid.png");
		teams.put(t10.name, t10);
		Team t11 = new Team("Paris Saint-Germain", "France", 2, root + "Paris_Saint-Germain.png");
		teams.put(t11.name, t11);
		Team t12 = new Team("Borussia Dortmund", "Germany", 2, root + "Borussia_Dortmund.png");
		teams.put(t12.name, t12);
		Team t13 = new Team("Sevilla", "Spain", 2, root + "sevilla.png");
		teams.put(t13.name, t13);
		Team t14 = new Team("Manchester City", "England", 2, root + "Manchester_City.png");
		teams.put(t14.name, t14);
		Team t15 = new Team("FC Porto", "Portugal", 2, root + "FC_Porto.png");
		teams.put(t15.name, t15);
		Team t16 = new Team("Manchester United", "England", 2, root + "Manchester_United.png");
		teams.put(t16.name, t16);
		Team t17 = new Team("Napoli", "Italy", 3, root + "Napoli.png");
		teams.put(t17.name, t17);
		Team t18 = new Team("Tottenham Hotspur", "England", 3, root + "Hotspur.png");
		teams.put(t18.name, t18);
		Team t19 = new Team("FC Basel", "Switzerland", 3, root + "FC_Basel.png");
		teams.put(t19.name, t19);
		Team t20 = new Team("Olympiacos", "Greece", 3, root + "Olympiacos_FC.png");
		teams.put(t20.name, t20);
		Team t21 = new Team("Anderlecht", "Belgium", 3, root + "R.S.C._Anderlecht.png");
		teams.put(t21.name, t21);
		Team t22 = new Team("Liverpool", "England", 3, root + "Liverpool.png");
		teams.put(t22.name, t22);
		Team t23 = new Team("AS Roma", "Italy", 3, root + "AS_Roma.png");
		teams.put(t23.name, t23);
		Team t24 = new Team("Besiktas", "Turkey", 3, root + "Besiktas.png");
		teams.put(t24.name, t24);
		Team t25 = new Team("Celtic FC", "Scotland", 4, root + "Celtic_FC.png");
		teams.put(t25.name, t25);
		Team t26 = new Team("CSKA Moscow", "Russia", 4, root + "PFK_CSKA.png");
		teams.put(t26.name, t26);
		Team t27 = new Team("Sporting CP", "Portugal", 4, root + "Sporting.png");
		teams.put(t27.name, t27);
		Team t28 = new Team("APOEL Nicosia", "Cyprus", 4, root + "APOEL.png");
		teams.put(t28.name, t28);
		Team t29 = new Team("Feyenoord", "Netherlands", 4, root + "Feyenoord.png");
		teams.put(t29.name, t29);
		Team t30 = new Team("NK Malibor", "Slovenia", 4, root + "Malibor.png");
		teams.put(t30.name, t30);
		Team t31 = new Team("Qarabag FK", "Azerbaijan", 4, root + "Qarabag.png");
		teams.put(t31.name, t31);
		Team t32 = new Team("RB Leipzig", "Germany", 4, root + "RB_Leipzig.png");
		teams.put(t32.name, t32);
		
		list.add(t1);
		list.add(t2);
		list.add(t3);
		list.add(t4);
		list.add(t5);
		list.add(t6);
		list.add(t7);
		list.add(t8);
		list.add(t9);
		list.add(t10);
		list.add(t11);
		list.add(t12);
		list.add(t13);
		list.add(t14);
		list.add(t15);
		list.add(t16);
		list.add(t17);
		list.add(t18);
		list.add(t19);
		list.add(t20);
		list.add(t21);
		list.add(t22);
		list.add(t23);
		list.add(t24);
		list.add(t25);
		list.add(t26);
		list.add(t27);
		list.add(t28);
		list.add(t29);
		list.add(t30);
		list.add(t31);
		list.add(t32);
		root = "/Users/Steveisno1/Documents/XJBjava/DrawSimulator/src";
		try {
			FileOutputStream fos = new FileOutputStream(root + "/1718ChampionsLeagueTeams.ser");
			ObjectOutputStream oos = new ObjectOutputStream(fos);
			oos.writeObject(list);
			oos.close();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
}