import java.awt.BorderLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.*;

public class Window extends JFrame{
	private JLabel title, groupA, groupB, groupC, groupD, groupE, groupF, groupG, groupH;
	private JLabel teamA1, teamA2, teamA3, teamA4;
	private JLabel teamB1, teamB2, teamB3, teamB4;
	private JLabel teamC1, teamC2, teamC3, teamC4;
	private JLabel teamD1, teamD2, teamD3, teamD4;
	private JLabel teamE1, teamE2, teamE3, teamE4;
	private JLabel teamF1, teamF2, teamF3, teamF4;
	private JLabel teamG1, teamG2, teamG3, teamG4;
	private JLabel teamH1, teamH2, teamH3, teamH4;
	private JLabel icon;
	private JButton roll;
	private ImageIcon imageicon;
	private Map<String, Group> groups;

	
	public Window(Map<String, Group> group) throws Exception {
		JFrame frame = new JFrame();
		groups = group;
		
		ImageIcon background = new ImageIcon(new ImageIcon("/Users/Steveisno1/Documents/XJBjava/DrawSimulator/images/523159398.jpg").getImage().getScaledInstance(800, 300, Image.SCALE_SMOOTH));
		JLabel pane1 = new JLabel(background);
		
		
		pane1.setLayout(new GridBagLayout());
		
		//JPanel pane1 = new JPanel(new GridBagLayout());
		JPanel pane2 = new JPanel(new GridBagLayout());
		
		//setContentPane(icon);
		
		title = new JLabel("17-18 UEFA Champions League Draw Simulator");
		title.setFont(new Font("Chalkduster", Font.PLAIN, 20));
		
		GridBagConstraints c = new GridBagConstraints();
		//c.fill = GridBagConstraints.HORIZONTAL;
		c.gridx = 0;
		c.gridy = 0;
		c.gridwidth = 12;
		pane1.add(title,c);
		
		c.gridx = 0;
		c.gridy = 1;
		roll = new JButton("Simulate");
		pane1.add(roll, c);
		
		c = new GridBagConstraints();
		//c.fill = GridBagConstraints.HORIZONTAL;
		c.gridx = 0;
		c.gridy = 2;
		c.gridwidth = 1;
		c.ipadx = 10;
		pane1.add(new JLabel(" "));
		c.gridx = 1;
		c.gridy = 2;
		c.gridwidth = 2;
		groupA = new JLabel("Group A");
		pane1.add(groupA, c);
		c.gridx = 3;
		c.gridy = 2;
		c.gridwidth = 1;
		pane1.add(new JLabel(" "));
		c.gridx = 4;
		c.gridy = 2;
		c.gridwidth = 2;
		groupB = new JLabel("Group B");
		pane1.add(groupB,c);
		c.gridx = 6;
		c.gridy = 2;
		c.gridwidth = 1;
		pane1.add(new JLabel(" "));
		c.gridx = 7;
		c.gridy = 2;
		c.gridwidth = 2;
		groupC = new JLabel("Group C");
		pane1.add(groupC,c);
		c.gridx = 9;
		c.gridy = 2;
		c.gridwidth = 1;
		pane1.add(new JLabel(" "));
		c.gridx = 10;
		c.gridy = 2;
		c.gridwidth = 2;
		groupD = new JLabel("Group D");
		pane1.add(groupD,c);
		c.gridx = 0;
		c.gridy = 3;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("A").team1.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 1;
		c.gridy = 3;
		c.gridwidth = 2;
		teamA1 = new JLabel(groups.get("A").team1.toString(), SwingConstants.LEFT);
		pane1.add(teamA1, c);
		c.gridx = 0;
		c.gridy = 4;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("A").team2.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 1;
		c.gridy = 4;
		c.gridwidth = 2;
		teamA2 = new JLabel(groups.get("A").team2.toString(), SwingConstants.LEFT);
		pane1.add(teamA2, c);
		c.gridx = 0;
		c.gridy = 5;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("A").team3.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 1;
		c.gridy = 5;
		c.gridwidth = 2;
		teamA3 = new JLabel(groups.get("A").team3.toString(), SwingConstants.LEFT);
		pane1.add(teamA3, c);
		c.gridx = 0;
		c.gridy = 6;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("A").team4.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 1;
		c.gridy = 6;
		c.gridwidth = 2;
		teamA4 = new JLabel(groups.get("A").team4.toString(), SwingConstants.LEFT);
		pane1.add(teamA4, c);
		
		
		c.gridx = 3;
		c.gridy = 3;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("B").team1.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 4;
		c.gridy = 3;
		c.gridwidth = 2;
		teamB1 = new JLabel(groups.get("B").team1.toString());
		pane1.add(teamB1, c);
		c.gridx = 3;
		c.gridy = 4;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("B").team2.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 4;
		c.gridy = 4;
		c.gridwidth = 2;
		teamB2 = new JLabel(groups.get("B").team2.toString());
		pane1.add(teamB2, c);
		c.gridx = 3;
		c.gridy = 5;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("B").team3.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 4;
		c.gridy = 5;
		c.gridwidth = 2;
		teamB3 = new JLabel(groups.get("B").team3.toString());
		pane1.add(teamB3, c);
		c.gridx = 3;
		c.gridy = 6;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("B").team4.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 4;
		c.gridy = 6;
		c.gridwidth = 2;
		teamB4 = new JLabel(groups.get("B").team4.toString());
		pane1.add(teamB4, c);
		
		
		c.gridx = 6;
		c.gridy = 3;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("C").team1.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 7;
		c.gridy = 3;
		c.gridwidth = 2;
		teamC1 = new JLabel(groups.get("C").team1.toString());
		pane1.add(teamC1, c);
		c.gridx = 6;
		c.gridy = 4;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("C").team2.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 7;
		c.gridy = 4;
		c.gridwidth = 2;
		teamC2 = new JLabel(groups.get("C").team2.toString());
		pane1.add(teamC2, c);
		c.gridx = 6;
		c.gridy = 5;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("C").team3.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 7;
		c.gridy = 5;
		c.gridwidth = 2;
		teamC3 = new JLabel(groups.get("C").team3.toString());
		pane1.add(teamC3, c);
		c.gridx = 6;
		c.gridy = 6;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("C").team4.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 7;
		c.gridy = 6;
		c.gridwidth = 2;
		teamC4 = new JLabel(groups.get("C").team4.toString());
		pane1.add(teamC4, c);
		
		
		c.gridx = 9;
		c.gridy = 3;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("D").team1.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 10;
		c.gridy = 3;
		c.gridwidth = 2;
		teamD1 = new JLabel(groups.get("D").team1.toString());
		pane1.add(teamD1, c);
		c.gridx = 9;
		c.gridy = 4;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("D").team2.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 10;
		c.gridy = 4;
		c.gridwidth = 2;
		teamD2 = new JLabel(groups.get("D").team2.toString());
		pane1.add(teamD2, c);
		c.gridx = 9;
		c.gridy = 5;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("D").team3.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 10;
		c.gridy = 5;
		c.gridwidth = 2;
		teamD3 = new JLabel(groups.get("D").team3.toString());
		pane1.add(teamD3, c);
		c.gridx = 9;
		c.gridy = 6;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("D").team4.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 10;
		c.gridy = 6;
		c.gridwidth = 2;
		teamD4 = new JLabel(groups.get("D").team4.toString());
		pane1.add(teamD4, c);
		c.gridx = 0;
		c.gridy = 7;
		c.gridwidth = 12;
		pane1.add(new JLabel(" "), c);
		
		c.gridx = 0;
		c.gridy = 8;
		c.gridwidth = 1;
		pane1.add(new JLabel(" "), c);
		c.gridx = 1;
		c.gridy = 8;
		c.gridwidth = 2;
		groupE = new JLabel("Group E");
		pane1.add(groupE,c);
		c.gridx = 3;
		c.gridy = 8;
		c.gridwidth = 1;
		pane1.add(new JLabel(" "), c);
		c.gridx = 4;
		c.gridy = 8;
		c.gridwidth = 2;
		groupF = new JLabel("Group F");
		pane1.add(groupF,c);
		c.gridx = 6;
		c.gridy = 8;
		c.gridwidth = 1;
		pane1.add(new JLabel(" "), c);
		c.gridx = 7;
		c.gridy = 8;
		c.gridwidth = 2;
		groupG = new JLabel("Group G");
		pane1.add(groupG,c);
		c.gridx = 9;
		c.gridy = 8;
		c.gridwidth = 1;
		pane1.add(new JLabel(" "), c);
		c.gridx = 10;
		c.gridy = 8;
		c.gridwidth = 2;
		groupH = new JLabel("Group H");
		pane1.add(groupH,c);
		
		
		c.gridx = 0;
		c.gridy = 9;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("E").team1.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 1;
		c.gridy = 9;
		c.gridwidth = 2;
		teamE1 = new JLabel(groups.get("E").team1.toString());
		pane1.add(teamE1, c);
		c.gridx = 0;
		c.gridy = 10;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("E").team2.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 1;
		c.gridy = 10;
		c.gridwidth = 2;
		teamE2 = new JLabel(groups.get("E").team2.toString());
		pane1.add(teamE2, c);
		c.gridx = 0;
		c.gridy = 11;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("E").team3.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 1;
		c.gridy = 11;
		c.gridwidth = 2;
		teamE3 = new JLabel(groups.get("E").team3.toString());
		pane1.add(teamE3, c);
		c.gridx = 0;
		c.gridy = 12;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("E").team4.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 1;
		c.gridy = 12;
		c.gridwidth = 2;
		teamE4 = new JLabel(groups.get("E").team4.toString());
		pane1.add(teamE4, c);
		
		
		c.gridx = 3;
		c.gridy = 9;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("F").team1.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 4;
		c.gridy = 9;
		c.gridwidth = 2;
		teamF1 = new JLabel(groups.get("F").team1.toString());
		pane1.add(teamF1, c);
		c.gridx = 3;
		c.gridy = 10;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("F").team2.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 4;
		c.gridy = 10;
		c.gridwidth = 2;
		teamF2 = new JLabel(groups.get("F").team2.toString());
		pane1.add(teamF2, c);
		c.gridx = 3;
		c.gridy = 11;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("F").team3.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 4;
		c.gridy = 11;
		c.gridwidth = 2;
		teamF3 = new JLabel(groups.get("F").team3.toString());
		pane1.add(teamF3, c);
		c.gridx = 3;
		c.gridy = 12;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("F").team4.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 4;
		c.gridy = 12;
		c.gridwidth = 2;
		teamF4 = new JLabel(groups.get("F").team4.toString());
		pane1.add(teamF4, c);
		
		
		c.gridx = 6;
		c.gridy = 9;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("G").team1.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 7;
		c.gridy = 9;
		c.gridwidth = 2;
		teamG1 = new JLabel(groups.get("G").team1.toString());
		pane1.add(teamG1, c);
		c.gridx = 6;
		c.gridy = 10;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("G").team2.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 7;
		c.gridy = 10;
		c.gridwidth = 2;
		teamG2 = new JLabel(groups.get("G").team2.toString());
		pane1.add(teamG2, c);
		c.gridx = 6;
		c.gridy = 11;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("G").team3.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 7;
		c.gridy = 11;
		c.gridwidth = 2;
		teamG3 = new JLabel(groups.get("G").team3.toString());
		pane1.add(teamG3, c);
		c.gridx = 6;
		c.gridy = 12;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("G").team4.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 7;
		c.gridy = 12;
		c.gridwidth = 2;
		teamG4 = new JLabel(groups.get("G").team4.toString());
		pane1.add(teamG4, c);
		
		c.gridx = 9;
		c.gridy = 9;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("H").team1.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 10;
		c.gridy = 9;
		c.gridwidth = 2;
		teamH1 = new JLabel(groups.get("H").team1.toString());
		pane1.add(teamH1, c);
		c.gridx = 9;
		c.gridy = 10;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("H").team2.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 10;
		c.gridy = 10;
		c.gridwidth = 2;
		teamH2 = new JLabel(groups.get("H").team2.toString());
		pane1.add(teamH2, c);
		c.gridx = 9;
		c.gridy = 11;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("H").team3.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 10;
		c.gridy = 11;
		c.gridwidth = 2;
		teamH3 = new JLabel(groups.get("H").team3.toString());
		pane1.add(teamH3, c);
		c.gridx = 9;
		c.gridy = 12;
		c.gridwidth = 1;
		imageicon = new ImageIcon(groups.get("H").team4.icon.getImage().getScaledInstance(15, 15, Image.SCALE_SMOOTH));
		icon = new JLabel();
		icon.setIcon(imageicon);
		pane1.add(icon, c);
		c.gridx = 10;
		c.gridy = 12;
		c.gridwidth = 2;
		teamH4 = new JLabel(groups.get("H").team4.toString());
		pane1.add(teamH4, c);
		
		
		frame.add(pane1);
		
		
		
		frame.setSize(800,300);
		frame.setLocationRelativeTo(null);
		frame.setVisible(true);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
	}
}